<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DegreeProgramSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('degree_programs')->insert([
            [
                'discipline_id' => 2,
                'degree' => 'Bachelor of Science in Computer Science and Engineering',
                'degree_code' => 'B.Sc. Engg. in CSE',
                'program_description' => '“Observe national & global trends, identify scope, produce market-ready graduates, and innovate for future” – that’s the only way today’s disciplines need to function; Computer Science and Engineering (CSE) discipline, Khulna University also follows this motto. Currently, our goal is to contribute in the process of achieving success in the 4th industrial revolution as well as to face the challenges of the 21st century.
In 1991, Computer Science and Engineering (CSE) Discipline of Khulna University (KU) started its academic activities with only 20 undergraduate students. Since then, around 850 undergraduate students have graduated from this Discipline. A perfect 100% proud graduates are working in different government and private organizations as well as in teaching professions in home and abroad.
Since its establishment, more than 850 students have graduated and are proudly working in the IT sector of various government and non-government organizations as well as in the teaching profession at home and abroad. At present, the discipline offers undergraduate & postgraduate programs including PhD programs. Faculties of CSE discipline have earned their PhDs from all over the world such as Canada, Australia, Japan, France, Norway, Korea, Malaysia, and etc. Faculty members with diverse interests are committed to research & innovation. At present, faculties of CSE are researching on the field of computer vision, machine learning, networking, software engineering, natural language processing, and so on.
This discipline provides quality education in both theoretical and applied fields and trains students to apply this education effectively to solve real-world problems. However, we firmly believe that academic learning can’t facilitate in producing complete national & global citizens. Thus, we have traditions of several mechanisms such as club activity, festival celebrations, study tours, and etc., to build up fully functional citizens. We also encourage students to participate in various sports for learning leadership-skills and team-work. Students of CSE are operating a computer club named Club for Updated Search on Computer (CLUSTER). CLUSTER arranges online/offline seminars, CSE Fests, programming contests and publishes IT magazines. Faculty members guide students to participate in competitions. Financial mechanisms are in place to facilitate students participating in both research and competitions.
A strong alumni community is helping graduates to be placed in big giants both in home and abroad. Furthermore, their continuous support helps students in need. They guide students to get hands-on knowledge about cutting edge technologies.
Finally, the discipline is in motion to achieve its maximum potential and contribute to society with utmost desire. An active student centric environment is promised to students. We’re looking forward to growing more through continuous creation and distribution of knowledge.',
                'major' => '',
                'school_id' => 2,
                'university_id' => 1,
                'location_id' => 1,
                'bnqf_level_id' => 7,
                'isced_id' => 2,
                'study_mode_id' => 1,
                'language_id' => 1,
                'applicable_session_id' => 1,
                'version' => 2024,
            ],
            [
                'discipline_id' => 3,
                'degree' => 'Bachelor of Science (Honours) in Forestry',
                'degree_code' => 'B. Sc. (Hon\'s.) in Forestry',
                'program_description' => '',
                'major' => '',
                'school_id' => 1,
                'university_id' => 1,
                'location_id' => 1,
                'bnqf_level_id' => 7,
                'isced_id' => 4,
                'study_mode_id' => 1,
                'language_id' => 1,
                'applicable_session_id' => 1,
                'version' => 2024,
            ],
            [
                'discipline_id' => 5,
                'degree' => 'Bachelor of Science in Environmental Science',
                'degree_code' => 'BSc in Eviron Sci',
                'program_description' => '',
                'major' => '',
                'school_id' => 1,
                'university_id' => 1,
                'location_id' => 1,
                'bnqf_level_id' => 7,
                'isced_id' => 5,
                'study_mode_id' => 1,
                'language_id' => 1,
                'applicable_session_id' => 1,
                'version' => 2024,
            ],
            [
                'discipline_id' => 6,
                'degree' => 'Bachelor of Science in Electronics and Communication Engineering',
                'degree_code' => 'B.Sc. Engg. (ECE)',
                'program_description' => '',
                'major' => '',
                'school_id' => 2,
                'university_id' => 1,
                'location_id' => 1,
                'bnqf_level_id' => 7,
                'isced_id' => 2,
                'study_mode_id' => 1,
                'language_id' => 1,
                'applicable_session_id' => 1,
                'version' => 2024,
            ],
            [
                'discipline_id' => 4,
                'degree' => 'Bachelor of Business Administration',
                'degree_code' => 'BBA',
                'program_description' => '',
                'major' => '1. Finance
2. Marketing
3. Human Resource Management
4. Operations and Supply Chain Management',
                'school_id' => 3,
                'university_id' => 1,
                'location_id' => 1,
                'bnqf_level_id' => 7,
                'isced_id' => 1,
                'study_mode_id' => 1,
                'language_id' => 1,
                'applicable_session_id' => 1,
                'version' => 2024,
            ],
            [
                'discipline_id' => 7,
                'degree' => 'Bachelor of Pharmacy (Honours)',
                'degree_code' => 'B. Pharm. (Hons.)',
                'program_description' => '',
                'major' => '',
                'school_id' => 1,
                'university_id' => 1,
                'location_id' => 1,
                'bnqf_level_id' => 7,
                'isced_id' => 6,
                'study_mode_id' => 1,
                'language_id' => 1,
                'applicable_session_id' => 1,
                'version' => 2024,
            ],
            [
                'discipline_id' => 8,
                'degree' => 'Bachelor of Social Science (Honours) in Development Studies',
                'degree_code' => 'BSS (Hons) in Development Studies',
                'program_description' => '',
                'major' => '',
                'school_id' => 4,
                'university_id' => 1,
                'location_id' => 1,
                'bnqf_level_id' => 7,
                'isced_id' => 7,
                'study_mode_id' => 1,
                'language_id' => 3,
                'applicable_session_id' => 1,
                'version' => 2024,
            ],
            [
                'discipline_id' => 9,
                'degree' => 'Bachelor of Science (Honours) in Statistics',
                'degree_code' => 'B. Sc. (Hon\'s) in Statistics',
                'program_description' => '',
                'major' => '',
                'school_id' => 2,
                'university_id' => 1,
                'location_id' => 1,
                'bnqf_level_id' => 7,
                'isced_id' => 8,
                'study_mode_id' => 1,
                'language_id' => 3,
                'applicable_session_id' => 1,
                'version' => 2024,
            ],
            [
                'discipline_id' => 10,
                'degree' => 'Bachelor of Science (Honours) in Soil, Water and Environment',
                'degree_code' => 'BSc (Hons) in SWE',
                'program_description' => '',
                'major' => '',
                'school_id' => 1,
                'university_id' => 1,
                'location_id' => 1,
                'bnqf_level_id' => 7,
                'isced_id' => 9,
                'study_mode_id' => 1,
                'language_id' => 3,
                'applicable_session_id' => 1,
                'version' => 2024,
            ],
            [
                'discipline_id' => 11,
                'degree' => 'Bachelor of Science (Honours) in Mathematics',
                'degree_code' => 'B. Sc. (Honours) in Mathematics',
                'program_description' => '',
                'major' => '',
                'school_id' => 2,
                'university_id' => 1,
                'location_id' => 1,
                'bnqf_level_id' => 7,
                'isced_id' => 10,
                'study_mode_id' => 1,
                'language_id' => 3,
                'applicable_session_id' => 1,
                'version' => 2024,
            ],
            [
                'discipline_id' => 12,
                'degree' => 'Bachelor of Arts (Honours) in History and Civilization',
                'degree_code' => 'B. A. (Hon\'s.) in History and Civilization',
                'program_description' => '',
                'major' => '',
                'school_id' => 5,
                'university_id' => 1,
                'location_id' => 1,
                'bnqf_level_id' => 7,
                'isced_id' => 11,
                'study_mode_id' => 1,
                'language_id' => 2,
                'applicable_session_id' => 1,
                'version' => 2024,
            ],
            [
                'discipline_id' => 13,
                'degree' => 'BACHELOR OF ARTS (HONOURS) IN BANGLA',
                'degree_code' => 'B.A. (Honours) in Bangla',
                'program_description' => '',
                'major' => '',
                'school_id' => 5,
                'university_id' => 1,
                'location_id' => 1,
                'bnqf_level_id' => 7,
                'isced_id' => 12,
                'study_mode_id' => 1,
                'language_id' => 1,
                'applicable_session_id' => 1,
                'version' => 2024,
            ],
            [
                'discipline_id' => 14,
                'degree' => 'Bachelor of Arts (Honours) in English',
                'degree_code' => 'BA (Hons) in English',
                'program_description' => '',
                'major' => '',
                'school_id' => 5,
                'university_id' => 1,
                'location_id' => 1,
                'bnqf_level_id' => 7,
                'isced_id' => 13,
                'study_mode_id' => 1,
                'language_id' => 3,
                'applicable_session_id' => 1,
                'version' => 2024,
            ],
            [
                'discipline_id' => 15,
                'degree' => 'Bachelor of Fine Arts (Honours) in Drawing and Painting',
                'degree_code' => 'B. F. A (Hon\'s.) in Drawing and Painting',
                'program_description' => '',
                'major' => '',
                'school_id' => 6,
                'university_id' => 1,
                'location_id' => 1,
                'bnqf_level_id' => 7,
                'isced_id' => 14,
                'study_mode_id' => 1,
                'language_id' => 1,
                'applicable_session_id' => 1,
                'version' => 2024,
            ],
            [
                'discipline_id' => 16,
                'degree' => 'Bachelor of Fine Arts (Honours) in Printmaking',
                'degree_code' => 'BFA (Hon\'s) in Printmaking',
                'program_description' => '',
                'major' => '',
                'school_id' => 6,
                'university_id' => 1,
                'location_id' => 1,
                'bnqf_level_id' => 7,
                'isced_id' => 15,
                'study_mode_id' => 1,
                'language_id' => 3,
                'applicable_session_id' => 1,
                'version' => 2024,
            ],
            [
                'discipline_id' => 17,
                'degree' => 'Bachelor of Social Science (Honours) in Mass Communication and Journalism',
                'degree_code' => 'BSS Honours in MCJ',
                'program_description' => '',
                'major' => '',
                'school_id' => 4,
                'university_id' => 1,
                'location_id' => 1,
                'bnqf_level_id' => 7,
                'isced_id' => 16,
                'study_mode_id' => 1,
                'language_id' => 3,
                'applicable_session_id' => 1,
                'version' => 2024,
            ],
            [
                'discipline_id' => 18,
                'degree' => 'Bachelor of Science in Fisheries (Honours)',
                'degree_code' => 'BSc in Fisheries (Honours)',
                'program_description' => '',
                'major' => '',
                'school_id' => 1,
                'university_id' => 1,
                'location_id' => 1,
                'bnqf_level_id' => 7,
                'isced_id' => 17,
                'study_mode_id' => 1,
                'language_id' => 3,
                'applicable_session_id' => 1,
                'version' => 2024,
            ],
            [
                'discipline_id' => 19,
                'degree' => 'Bachelor of Business Administration in Human Resource Management',
                'degree_code' => 'BBA in HRM',
                'program_description' => '',
                'major' => '',
                'school_id' => 3,
                'university_id' => 1,
                'location_id' => 1,
                'bnqf_level_id' => 7,
                'isced_id' => 1,
                'study_mode_id' => 1,
                'language_id' => 3,
                'applicable_session_id' => 1,
                'version' => 2024,
            ],
            [
                'discipline_id' => 20,
                'degree' => 'Bachelor of Fine Arts (Honours) in Sculpture',
                'degree_code' => 'BFA (Hon\'s) in Sculpture',
                'program_description' => '',
                'major' => '',
                'school_id' => 6,
                'university_id' => 1,
                'location_id' => 1,
                'bnqf_level_id' => 7,
                'isced_id' => 18,
                'study_mode_id' => 1,
                'language_id' => 3,
                'applicable_session_id' => 1,
                'version' => 2024,
            ],
            [
                'discipline_id' => 21,
                'degree' => 'Bachelor of Education (Honours)',
                'degree_code' => 'BEd (Hons.)',
                'program_description' => '',
                'major' => '',
                'school_id' => 7,
                'university_id' => 1,
                'location_id' => 1,
                'bnqf_level_id' => 7,
                'isced_id' => 17,
                'study_mode_id' => 1,
                'language_id' => 3,
                'applicable_session_id' => 1,
                'version' => 2024,
            ],
            [
                'discipline_id' => 22,
                'degree' => 'Title of the Academic Program',
                'degree_code' => 'ML',
                'program_description' => 'Certificate Course in Arabic language
Certificate Course in Chinese language
Certificate Course in English language
Certificate Course in French language
Certificate Course in German language
Certificate Course in Japanese language
Certificate Course in Korean language
Certificate Course in Persian language
Certificate Course in Spanish language',
                'major' => '',
                'school_id' => 8,
                'university_id' => 1,
                'location_id' => 1,
                'bnqf_level_id' => 4,
                'isced_id' => 13,
                'study_mode_id' => 2,
                'language_id' => 1,
                'applicable_session_id' => 1,
                'version' => 2024,
            ],
            // Add more degree programs as needed
        ]);
    }
}