<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DisciplineSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $disciplines = [
            ['school_id' => 2, 'name' => 'Architecture Discipline', 'short_name' => 'ARCH', 'vision' => 'Architecture Discipline, Khulna University (ArchKU) aspires to become a centre of academic excellence in producing graduates who would advocate moral values, context, inquiry and research, problem-solving, synthesis, leadership, and lifelong learning in creating a healthy built environment while addressing the emerging needs and challenges of societies.', 'web_link' => '', 'version' => 2024],
            ['school_id' => 2, 'name' => 'Computer Science and Engineering Discipline', 'short_name' => 'CSE', 'vision' => 'To be one of the global leaders in the fields of CSE and ICT through quality education, excellent research, and innovation for the sustainable transformation of the society.', 'web_link' => '', 'version' => 2024],
            ['school_id' => 1, 'name' => 'Forestry and Wood Technology Discipline', 'short_name' => 'FWT', 'vision' => 'Becoming the centre of excellence in teaching and research in the field of forestry and wood science nationally and globally for 21st century.', 'web_link' => '', 'version' => 2024],
            ['school_id' => 3, 'name' => 'Business Administration Discipline', 'short_name' => 'BA', 'vision' => 'We envisage ourselves as a leading international business school and aspire to redefine the roles of business professionals and academicians for driving changes in global business and bringing social transformations.', 'web_link' => '', 'version' => 2024],
            ['school_id' => 1, 'name' => 'Environmental Science Discipline', 'short_name' => 'ES', 'vision' => 'The vision of the Environmental Science Discipline in Khulna University is to stride for achieving a healthy environment supportive of robust ecosystems by and for all life on the Earth and beyond', 'web_link' => '', 'version' => 2024],
            ['school_id' => 2, 'name' => 'Electronics and Communication Engineering Discipline', 'short_name' => 'ECE', 'vision' => 'Striving to build a knowledge-based society employing technological capabilities.', 'web_link' => '', 'version' => 2024],
            ['school_id' => 1, 'name' => 'Pharmacy Discipline', 'short_name' => '', 'vision' => 'To achieve excellence and leadership in sustainable and innovative pharmacy education, research and practice for the wellness of the society.', 'web_link' => '', 'version' => 2024],
            ['school_id' => 4, 'name' => 'Development Studies', 'short_name' => 'DS', 'vision' => 'Development Studies discipline intends to see the world with equal opportunities for all in respect of the access to resources, human rights, freedom and dignity through which the true meaning of development is realised by excelling in teaching and research on doing development.', 'web_link' => '', 'version' => 2024],
            ['school_id' => 2, 'name' => 'Statistics Discipline', 'short_name' => 'STAT', 'vision' => 'Develop the next generation of statistics professionals by achieving excellence in teaching and research to meet the increasing demand for Statistics.', 'web_link' => '', 'version' => 2024],
            ['school_id' => 1, 'name' => 'Soil, Water and Environment Discipline', 'short_name' => 'SWE', 'vision' => 'Conservation and management of soil, water and environment for achieving healthy ecosystems to ensure food, water and nutrition security for the survival and sustainable development of all forms of life.', 'web_link' => '', 'version' => 2024],
            ['school_id' => 2, 'name' => 'Mathematics Discipline', 'short_name' => 'MATH', 'vision' => 'The vision of the Mathematics Discipline of Khulna University is to be recognized internationally for excellence in research and teaching and nationally for high quality service to be a world class discipline and able to contribute to today’s society.', 'web_link' => '', 'version' => 2024],
            ['school_id' => 5, 'name' => 'History and Civilization Discipline', 'short_name' => 'HC', 'vision' => 'Become the center of excellence in teaching and research in the field of history (national and international) and civilization for 21st century.', 'web_link' => '', 'version' => 2024],
            ['school_id' => 5, 'name' => 'Bangla Discipline (বাংলা বিভাগ)', 'short_name' => 'BANGLA', 'vision' => 'The vision of Bangla Discipline (বাংলা বিভাগ) is to make it a centre of excellence in research and teaching-learning on literature, language and culture.', 'web_link' => '', 'version' => 2024],
            ['school_id' => 5, 'name' => 'English Discipline', 'short_name' => 'ENGLISH', 'vision' => 'English Discipline envisions to produce successive generations of future-ready graduates with mastery in English studies and glocal perspectives to cope with challenges of the contemporary world and perform proactively in the ever-changing knowledge-based society.', 'web_link' => '', 'version' => 2024],
            ['school_id' => 6, 'name' => 'Drawing and Painting Discipline', 'short_name' => 'DP', 'vision' => 'Vision of the Drawing and Painting discipline is to establish a strong, helpful and sustainable current Fine Art network, working together to preserve the future of artists in Bangladesh. The discipline aspires to prepare students for the creation, practice, study, criticism, and teaching of visual arts in a context that emphasizes cultural diversity, creative activity, research, liberal education, public engagement and technical innovation.', 'web_link' => '', 'version' => 2024],
            ['school_id' => 6, 'name' => 'Printmaking Discipline', 'short_name' => 'PrintMaking', 'vision' => 'Producing knowledge and achieving professional aptitude in an artistic framework that leads the integrated endeavors toward developing a creative environment in Printmaking across the world.', 'web_link' => '', 'version' => 2024],
            ['school_id' => 4, 'name' => 'Mass Communication and Journalism Discipline', 'short_name' => 'MCJ', 'vision' => 'The vision of Mass Communication and Journalism Discipline is to encourage a free and balanced flow of information, opinion, and entertainment across all communication networks and to create a discerning and democratic society. The objectives of Mass Communication and Journalism discipline are to offer quality education and conduct research in the field of Communication, Media, and Journalism through various programs, such as Bachelor, Masters and PhD, which will contribute to human communication, journalism, sustainable media management, digital media industry, and development resources. Discipline Mission', 'web_link' => '', 'version' => 2024],
            ['school_id' => 1, 'name' => 'Fisheries and Marine Resource Technology Discipline', 'short_name' => 'FMRT', 'vision' => 'To be a globally recognized center of excellence in education, research, entrepreneurs for sustainable fisheries and marine resource development.', 'web_link' => '', 'version' => 2024],
            ['school_id' => 3, 'name' => 'Human Resource Management Discipline', 'short_name' => 'HRM', 'vision' => 'The program is designed to become the center of excellence in Human Resource education and research to contribute in the field of Human Resource Management nationally and internationally.', 'web_link' => '', 'version' => 2024],
            ['school_id' => 6, 'name' => 'Sculpture Discipline', 'short_name' => 'Sculpture', 'vision' => 'The Sculpture Discipline will lead in promoting the sculpting as well as visual arts by fostering critical and creative thinking, artistic expression, effective communication, cultural awareness, and social engagement. This Discipline seeks to become an international model in the field of sculpture and visual arts through research that promotes positive and sustainable change in our global community.', 'web_link' => '', 'version' => 2024],
            ['school_id' => 7, 'name' => 'Education Discipline', 'short_name' => 'EDU', 'vision' => 'To realise and propagate the philosophy of education in Bangladesh and construct, maintain, and become a significant contributor to the apparatus supporting it, at all levels and in all aspects of education in Bangladesh, ultimately bringing about a knowledge-based society capable of competing and triumphing on a global scale.', 'web_link' => '', 'version' => 2024],
            ['school_id' => 8, 'name' => 'Modern Language Center', 'short_name' => 'ML', 'vision' => 'Modern Language Center of Khulna University intends to make the learners proficient in different modern foreign languages so that they can cope up with the people of those countries or nations and can involve themselves in higher education, works and different activities in the certain countries through reading, writing, listening and speaking.', 'web_link' => '', 'version' => 2024],
            ['school_id' => 4, 'name' => 'Economics Discipline', 'short_name' => 'ECON', 'vision' => 'To establish Economics Discipline as a center of excellence in teaching, learning, research, industry-academia linkage, leadership, and community service.', 'web_link' => '', 'version' => 2024],
            ['school_id' => 9, 'name' => 'Law Discipline', 'short_name' => 'LLB', 'vision' => 'Law Discipline of Khulna University nourishes the creativity dormant in the students with a view to preparing excellent legal minds as well as professionals. The aim of the Discipline is to prepare their graduates to serve the national and global fields by utilising their excellent thinking, integrity and sense of professionalism so that they can build a world of equality and justice and keep their signature in the development of Law.', 'web_link' => '', 'version' => 2024],
            ['school_id' => 2, 'name' => 'Chemistry Discipline', 'short_name' => 'CHEM', 'vision' => 'Chemistry Discipline endeavours to be a nationally recognized model for educating and graduating students prepared to compete in and contribute to the ever-changing, technology-centred world. Our focus is to achieving excellence and leadership in chemistry-based teaching, fundamental research and innovative applications to ensure industrial and socio-economic development of Bangladesh.', 'web_link' => '', 'version' => 2024],
            ['school_id' => 2, 'name' => 'Physics Discipline', 'short_name' => 'PHY', 'vision' => 'To build a foundation for excellence and spur development for the graduates of the discipline by igniting and nurturing enthusiasm, interests, and passion for the creation of knowledge through teaching and research in physics for professional courses as a part of the curricula. To help create a scientific society that encourages logical thinking.', 'web_link' => '', 'version' => 2024],
            ['school_id' => 2, 'name' => 'Urban and Rural Planning Discipline', 'short_name' => 'URP', 'vision' => 'Producing knowledge and achieving professional aptitude in an artistic framework that leads the integrated endeavors toward developing a creative environment in Printmaking across the world.', 'web_link' => '', 'version' => 2024],
            ['school_id' => 4, 'name' => 'Sociology Discipline', 'short_name' => 'Sociology', 'vision' => 'To generate human resources with academic excellence in theoretical and pragmatic knowledge of Sociology by ensuring students friendly education and field-based social research as well as achieving sociological imagination on social milieu to cope with the ever changing world.', 'web_link' => '', 'version' => 2024],
        ];

        // Insert data into the disciplines table
        DB::table('disciplines')->insert($disciplines);
    }
}
